### PR TITLE
nuget.exe restore <projectFileName>, where the project contains a packages.config works now

### PR DESCRIPTION
**Pull request by deepakaravindr**
Fixes https://github.com/NuGet/Home/issues/1313

nuget.exe restore < projectFileName >, where the project contains a
packages.config works now

@yishaigalatzer @MeniZalzman @emgarten @feiling @zhili1208

### CODE REVIEW

**Comment by emgarten** [comment]
:shipit:

**Comment by deepakaravindr** [comment]
@yishaigalatzer,

We already seem to have tests that are indirectly using csproj file as input, both for project.json and project.< projectName >.json scenarios

RestoreProjectJson_GenerateTargetsFileFromCSProj and
RestoreProjectJson_GenerateFilesWithProjectNameFromCSProj

**Comment by zhili1208** [comment]
:shipit:

**Comment by johnataylor** [comment]
:shipit:

**Pull request merged**
