### PR TITLE
* Only include project references that have project.json when conside…

### PR DESCRIPTION
**Pull request by pranavkm**
…ring

the build integrated transitive closure.
- Remove cyclic dependencies from external project dependencies.

### CODE REVIEW

**Comment by pranavkm** [comment]
cc @anurse  \ @yishaigalatzer

**Comment by yishaigalatzer** [comment]
looks good

**Comment by pranavkm** [comment]
Test: https://github.com/NuGet/NuGet.VisualStudioExtension/pull/44

**Comment by analogrelay** [comment]
To be clear, this means that if I have three projects:
- `Project1` - Has a project.json
  - References `Project2`
- `Project2` - No project.json
  - References `Project3`
- `Project3` - Has a project.json

Then restoring `Project1` will **not** restore any of the packages from `Project3`'s project.json. I'm not really opposed since it would be odd for `Project2` to not have a project.json (though in theory if it has no package dependencies it could be allowed, I guess) and we can call that scenario unsupported, but I want to bring it up to make sure it is considered.

**Comment by pranavkm** [comment]
> Then restoring Project1 will not restore any of the packages from Project3's project.json.

That's not actually true - we get the full closure when we ask for Project1's closure. Consequently we _will_ restore and transitively reference packages referenced in `Project3`'s project.json. We simply avoid considering `Project2` as an external reference.

**Pull request merged**
