### PR TITLE
Change dll versions to 3.2

### PR DESCRIPTION
**Pull request by feiling**
@zhili1208 @emgarten @deepakaravindr @yishaigalatzer 

Note that this fixes the versions of the DLLs. But the package versions are specified in the build scripts which I've already updated.

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
:shipit:  - Same questions as before, are versions exposed from elsewhere?

**Comment by feiling** [comment]
No, didn't find other places that expose the version number.

**Comment by emgarten** [comment]
Use 3.2.0 not 3.2 :watch:

**Comment by feiling** [comment]
Version changed to "3.2.0"

**Comment by feiling** [comment]
merged and pushed.

**Pull request closed without merging**
